workflows:
  android-build:
    name: Build Android App
    environment:
      java: 17
    scripts:
      - name: Set up permissions
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/**/*.apk
